### ISSUE TITLE
error please note cuda version should >= 11.3 when compiled with cuda 11 `torch_dtype` is deprecated! Use `dtype` instead!

### ISSUE THREAD

**Issue by merecesarchviz** [ekwek1/soprano#43]
@ekwek1 I install all without errors but when i try to run i got this error!:

<img width="1842" height="521" alt="Image" src="https://github.com/user-attachments/assets/caecada3-0c2e-449a-abf5-f82561741574" />

**Comment by ekwek1** [comment]
The message about dll path and torch_dtype are normal when using LMDeploy, the error message is the line after this:
Check failed: status == cudaSuccess no kernel image is available for execution on the device

Please let me know your installed version of LMDeploy and Pytorch. Also, does it work when not using the LMDeploy backend? You can test this with:
```
soprano-webui --backend transformers
```

**Comment by merecesarchviz** [comment]
> The message about dll path and torch_dtype are normal when using LMDeploy, the error message is the line after this: Check failed: status == cudaSuccess no kernel image is available for execution on the device
> 
> Please let me know your installed version of LMDeploy and Pytorch. Also, does it work when not using the LMDeploy backend? You can test this with:
> 
> ```
> soprano-webui --backend transformers
> ```

that solve it, now it is working, thank you for the help
